import { AppCardItem, AppCategory } from '../types';

export const APP_CATEGORIES: { id: AppCategory; label: string; count?: number }[] = [
  { id: 'all', label: 'All Document Tools' },
  { id: 'converters', label: 'Converters' },
  { id: 'organization', label: 'Merge & Organize' },
  { id: 'optimization', label: 'Optimization' },
  { id: 'security_ocr', label: 'OCR & Security' },
];

export const APP_CATALOG: AppCardItem[] = [
  {
    id: 'pdf-to-docx',
    title: 'PDF to Word (.docx) Converter',
    shortName: 'PDF to Word',
    description: 'Transform complex PDFs into fully editable Microsoft Word documents with 100% editable text, preserved font styles, tables, and aligned image figures.',
    category: 'converters',
    status: 'active',
    badge: 'Ready to Use',
    iconName: 'FileText',
    accentGradient: 'from-blue-600 to-indigo-600',
    glowColor: 'group-hover:shadow-blue-500/25',
    borderHover: 'hover:border-blue-500/50',
    features: [
      'Editable Word typography (Paragraphs, Headings, Lists)',
      'Spatial figure & image isolation (no rasterized text)',
      'Intelligent tabular grid reconstruction',
      'Batch queue & ZIP download',
      '100% In-browser private processing',
    ],
    supportedFormats: ['.pdf → .docx'],
    popular: true,
  },
  {
    id: 'pdf-merge-split',
    title: 'PDF Merger & Page Splitter',
    shortName: 'Merge & Split',
    description: 'Combine multiple PDF documents into a single cohesive file, re-order pages, or extract specific page ranges with visual thumbnail grid selection.',
    category: 'organization',
    status: 'active',
    badge: 'Ready to Use',
    iconName: 'Layers',
    accentGradient: 'from-emerald-600 to-teal-600',
    glowColor: 'group-hover:shadow-emerald-500/25',
    borderHover: 'hover:border-emerald-500/50',
    features: [
      'Multi-document sequential PDF merger with page inspection',
      'Visual thumbnail grid & multi-select page extractor',
      'Lossless vector page rotation (90°, 180°, 270°)',
      'Split all pages into single PDFs (ZIP archive)',
      'Equal page chunk partitioning & custom syntax ranges',
    ],
    supportedFormats: ['.pdf → .pdf, .zip'],
    popular: true,
  },
  {
    id: 'pdf-page-numbers',
    title: 'PDF Page Numbers (Header & Footer)',
    shortName: 'PDF Page Numbers',
    description: 'Add clean, customizable page numbers, headers, and footers into any PDF with 6-point visual positioning, Roman/Alpha formats, and cover page exclusions.',
    category: 'organization',
    status: 'active',
    badge: 'Ready to Use',
    iconName: 'Hash',
    accentGradient: 'from-sky-600 to-blue-600',
    glowColor: 'group-hover:shadow-sky-500/25',
    borderHover: 'hover:border-sky-500/50',
    features: [
      '6-point anchor grid (Top/Bottom Left, Center, Right)',
      'Page X of Y, Roman (i, ii), Alphabetical & custom templates',
      'Cover page skipping & custom page range selection',
      'Alternating outer/inner margins for 2-sided booklet printing',
      'Real-time interactive canvas preview & custom fonts/colors',
    ],
    supportedFormats: ['.pdf → .pdf (Numbered)'],
    popular: true,
  },
  {
    id: 'powerpoint-to-pdf',
    title: 'PowerPoint to PDF',
    shortName: 'PowerPoint to PDF',
    description: 'Convert Microsoft PowerPoint (.pptx) slide decks and presentations into professional PDF documents with customizable themes, slide layouts, and formatting.',
    category: 'converters',
    status: 'active',
    badge: 'Ready to Use',
    iconName: 'Presentation',
    accentGradient: 'from-indigo-600 to-purple-600',
    glowColor: 'group-hover:shadow-indigo-500/25',
    borderHover: 'hover:border-indigo-500/50',
    features: [
      'Convert PowerPoint (.pptx) presentations into high-quality PDF files',
      'Interactive slide preview with custom corporate and dark themes',
      'Preset templates for executive reviews and product launch decks',
      'Configurable page sizes, widescreen layouts, and slide numbering',
    ],
    supportedFormats: ['.pptx → .pdf'],
    popular: true,
  },
  {
    id: 'pdf-to-pptx',
    title: 'PDF to PowerPoint',
    shortName: 'PDF to PowerPoint',
    description: 'Convert PDF document pages and presentations into editable Microsoft PowerPoint (.pptx) slide decks with high-resolution images and text formatting.',
    category: 'converters',
    status: 'active',
    badge: 'Ready to Use',
    iconName: 'Presentation',
    accentGradient: 'from-amber-600 to-orange-600',
    glowColor: 'group-hover:shadow-amber-500/25',
    borderHover: 'hover:border-amber-500/50',
    features: [
      'Convert multi-page PDF documents into PowerPoint (.pptx) decks',
      'Slide aspect ratio selection (16:9 widescreen & 4:3 standard)',
      'High-resolution slide image rendering and text layout extraction',
      'Interactive slide navigator & full-screen presentation preview',
    ],
    supportedFormats: ['.pdf → .pptx'],
    popular: true,
  },
  {
    id: 'excel-to-pdf',
    title: 'Excel to PDF',
    shortName: 'Excel to PDF',
    description: 'Convert Microsoft Excel spreadsheets (.xlsx, .xls, .csv) into professional PDF documents with customizable worksheets, table themes, and layout orientations.',
    category: 'converters',
    status: 'active',
    badge: 'Ready to Use',
    iconName: 'FileSpreadsheet',
    accentGradient: 'from-emerald-600 to-teal-600',
    glowColor: 'group-hover:shadow-emerald-500/25',
    borderHover: 'hover:border-emerald-500/50',
    features: [
      'Convert Excel spreadsheets and CSVs into printable PDF files',
      'Multi-sheet worksheet selector & interactive table preview',
      'Custom table themes (Corporate, Clean Light, Dark Mode)',
      'Configurable page sizes (A4, Letter, Legal) & orientations',
    ],
    supportedFormats: ['.xlsx, .xls, .csv → .pdf'],
    popular: true,
  },
  {
    id: 'edit-pdf',
    title: 'Edit PDF',
    shortName: 'Edit PDF',
    description: 'Edit and annotate PDF documents directly in your browser by adding text stamps, badges, highlights, and annotations with visual page previews.',
    category: 'organization',
    status: 'active',
    badge: 'Ready to Use',
    iconName: 'Edit3',
    accentGradient: 'from-indigo-600 to-violet-600',
    glowColor: 'group-hover:shadow-indigo-500/25',
    borderHover: 'hover:border-indigo-500/50',
    features: [
      'Interactive PDF page rendering and multi-page navigation',
      'Add custom text stamps, badges, and highlight annotations',
      'Lossless vector annotation embedding via pdf-lib',
      'Instant download of modified PDF documents',
    ],
    supportedFormats: ['.pdf → .pdf (Edited)'],
    popular: true,
  },
  {
    id: 'html-to-pdf',
    title: 'HTML to PDF',
    shortName: 'HTML to PDF',
    description: 'Convert HTML markup, web pages, invoices, reports, and code snippets into crisp, professional PDF documents with customizable page sizes, orientations, and margins.',
    category: 'converters',
    status: 'active',
    badge: 'Ready to Use',
    iconName: 'Code',
    accentGradient: 'from-emerald-600 to-teal-600',
    glowColor: 'group-hover:shadow-emerald-500/25',
    borderHover: 'hover:border-emerald-500/50',
    features: [
      'Live HTML editor & instant rendered preview',
      'Preset templates for professional invoices and executive reports',
      'Configurable page sizes (A4, Letter, Legal) & orientations',
      'High-resolution canvas rendering and multi-page pagination',
    ],
    supportedFormats: ['.html, .htm → .pdf'],
    popular: true,
  },
  {
    id: 'pdf-crop',
    title: 'Crop PDF',
    shortName: 'Crop PDF',
    description: 'Crop PDF page margins, remove unwanted whitespace, trim page bounding boxes visually, or apply custom crop coordinates across all or selected pages.',
    category: 'organization',
    status: 'active',
    badge: 'Ready to Use',
    iconName: 'Crop',
    accentGradient: 'from-indigo-600 to-violet-600',
    glowColor: 'group-hover:shadow-indigo-500/25',
    borderHover: 'hover:border-indigo-500/50',
    features: [
      'Visual box crop & margin trimming (Top, Bottom, Left, Right)',
      'Apply crop to all pages, odd/even pages, or specific custom ranges',
      'Live interactive PDF page preview with movable crop handles',
      'Lossless vector page re-bounding and file size optimization',
    ],
    supportedFormats: ['.pdf → .pdf (Cropped)'],
    popular: true,
  },
  {
    id: 'pdf-compress',
    title: 'PDF Compressor & Optimizer',
    shortName: 'Compress PDF',
    description: 'Reduce PDF file sizes dramatically for email attachments and web sharing with adaptive image resampling, stream compression, and quality comparison.',
    category: 'optimization',
    status: 'active',
    badge: 'Ready to Use',
    iconName: 'Minimize2',
    accentGradient: 'from-amber-600 to-orange-600',
    glowColor: 'group-hover:shadow-amber-500/25',
    borderHover: 'hover:border-amber-500/50',
    features: [
      'Extreme, Recommended, and High-Quality presets',
      'Custom resolution scaling and JPEG quality sliders',
      'Grayscale scanned document optimization',
      'Interactive side-by-side visual quality comparison',
      'Batch compression with ZIP download',
    ],
    supportedFormats: ['.pdf → .pdf (Compressed), .zip'],
    popular: true,
  },
  {
    id: 'pdf-ocr-extract',
    title: 'OCR PDF (Searchable & Selectable)',
    shortName: 'OCR PDF',
    description: 'Convert scanned paper PDFs and photo documents into searchable, selectable PDF documents with embedded text layers and multi-format export.',
    category: 'security_ocr',
    status: 'active',
    badge: 'Ready to Use',
    iconName: 'ScanText',
    accentGradient: 'from-purple-600 to-violet-600',
    glowColor: 'group-hover:shadow-purple-500/25',
    borderHover: 'hover:border-purple-500/50',
    features: [
      'Convert scanned PDFs into searchable & selectable documents',
      'Embedded invisible text layer aligned with scanned page coordinates',
      'Multi-language optical character recognition (English, Spanish, etc.)',
      'Interactive side-by-side text inspector & live keyword search',
      'Export to Searchable PDF, Plain Text (.txt), Markdown & JSON',
    ],
    supportedFormats: ['.pdf, .png, .jpg, .webp → .pdf (Searchable), .txt, .md, .json'],
    popular: true,
  },
  {
    id: 'image-to-pdf',
    title: 'Images to PDF Packager (JPG, PNG, WebP)',
    shortName: 'Images to PDF Packager',
    description: 'Convert collections of photos, screenshots, and scanned receipts (JPG, PNG, WebP, BMP) into clean, standard PDF documents with customizable page margins & multi-image layouts.',
    category: 'converters',
    status: 'active',
    badge: 'Ready',
    iconName: 'Image',
    accentGradient: 'from-rose-600 to-pink-600',
    glowColor: 'group-hover:shadow-rose-500/25',
    borderHover: 'hover:border-rose-500/50',
    features: [
      'Batch image sorting, drag reorder & page sizing (A4, Letter, Auto/Fit)',
      '1-up, 2-up, and 4-up contact sheet grid layouts',
      'Per-image rotation, custom margins, and lossless compression',
    ],
    supportedFormats: ['.jpg, .png, .webp, .bmp → .pdf'],
    popular: true,
  },
  {
    id: 'pdf-to-excel',
    title: 'PDF Tables to Excel (.xlsx)',
    shortName: 'PDF to Excel',
    description: 'Detect, extract, and convert structured data tables, payroll rosters, and financial balance sheets from PDF reports into clean Microsoft Excel (.xlsx) workbooks.',
    category: 'converters',
    status: 'active',
    badge: 'Ready',
    iconName: 'Table',
    accentGradient: 'from-cyan-600 to-blue-600',
    glowColor: 'group-hover:shadow-cyan-500/25',
    borderHover: 'hover:border-cyan-500/50',
    features: [
      'Multi-page table alignment & spanning columns',
      'Formula & numeric/currency data type formatting',
      'Clean .xlsx, .csv, and TSV workbook exports',
    ],
    supportedFormats: ['.pdf → .xlsx, .csv, .tsv, .json'],
    popular: true,
  },
  {
    id: 'pdf-protect-watermark',
    title: 'PDF Security, Watermark & Sign',
    shortName: 'Protect & Watermark',
    description: 'Add custom text & tiled watermarks, official rubber stamps, calligraphic or hand-drawn digital signatures, blackout redactions, and metadata sanitation to PDF documents.',
    category: 'security_ocr',
    status: 'active',
    badge: 'Ready',
    iconName: 'ShieldCheck',
    accentGradient: 'from-sky-600 to-indigo-600',
    glowColor: 'group-hover:shadow-sky-500/25',
    borderHover: 'hover:border-sky-500/50',
    features: [
      'Text watermarks (diagonal, grid tile, banners)',
      'Official rubber stamp presets & custom seals',
      'Digital signature pad & cursive calligraphy',
      'Blackout redactions & metadata sanitization',
    ],
    supportedFormats: ['.pdf → .pdf (Secured & Signed)'],
    popular: true,
  },
  {
    id: 'pdf-to-image',
    title: 'PDF to Image Converter (PNG, JPG, WebP)',
    shortName: 'PDF to Image',
    description: 'Render and extract PDF pages into high-resolution PNG, JPG, or WebP images with customizable DPI scaling (72 to 600 DPI), visual page selection, and batch ZIP export.',
    category: 'converters',
    status: 'active',
    badge: 'Ready',
    iconName: 'FileImage',
    accentGradient: 'from-teal-600 to-emerald-600',
    glowColor: 'group-hover:shadow-emerald-500/25',
    borderHover: 'hover:border-emerald-500/50',
    features: [
      'Ultra-HD DPI rendering (72 to 600 DPI print quality)',
      'Export to PNG (lossless), JPEG (compact), & WebP',
      'Visual multi-page selector & ZIP batch archive packaging',
      'Color mode filters: Full Color, Grayscale & Binarization',
      'Instant clipboard copy & side-by-side high-res inspector',
    ],
    supportedFormats: ['.pdf → .png, .jpg, .webp, .zip'],
    popular: true,
  },
];
